# Generated by Django 4.2.27 on 2026-02-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='core_client_user_id_bbc8a6_idx',
            old_name='core_client_user_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='core_client_user_id_0c2870_idx',
            old_name='core_client_user_name_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='core_projec_user_id_1f79a6_idx',
            old_name='core_project_user_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='core_projec_user_id_d18d5a_idx',
            old_name='core_project_user_name_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='core_projec_client__f4eed2_idx',
            old_name='core_project_client_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_user_id_2fc83e_idx',
            old_name='core_task_user_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_project_3c46c4_idx',
            old_name='core_task_project_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_project_62461d_idx',
            old_name='core_task_project_priority_idx',
        ),
    ]
