# Generated by Django 4.2.27 on 2026-02-17 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSyncBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_uuid', models.CharField(max_length=100, unique=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('sync_status', models.CharField(default='pending', max_length=20)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offline_sync_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimerSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('total_elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('total_break_seconds', models.PositiveIntegerField(default=0)),
                ('started_from', models.CharField(default='web', max_length=30)),
                ('offline_mode', models.BooleanField(default=False)),
                ('local_session_uuid', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_sessions', to='core.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_sessions', to='core.task')),
            ],
            options={
                'db_table': 'timer_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_manual', models.BooleanField(default=False)),
                ('source', models.CharField(default='timer', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('is_billable', models.BooleanField(default=True)),
                ('hourly_rate_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('local_entry_uuid', models.CharField(blank=True, max_length=100)),
                ('sync_status', models.CharField(default='synced', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.task')),
            ],
            options={
                'db_table': 'time_entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimerBreak',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('break_started_at', models.DateTimeField()),
                ('break_ended_at', models.DateTimeField(blank=True, null=True)),
                ('break_duration_seconds', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timer_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='core.timersession')),
            ],
            options={
                'db_table': 'timer_breaks',
                'ordering': ['-created_at'],
            },
        ),
    ]
