# Generated by Django 4.2.27 on 2026-02-17 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoicing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRiskAlert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('context_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='core.client')),
            ],
            options={
                'db_table': 'client_risk_alerts',
            },
        ),
        migrations.CreateModel(
            name='ClientTrustRuleConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=100)),
                ('on_time_weight', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('delay_penalty_weight', models.DecimalField(decimal_places=2, default=25, max_digits=6)),
                ('overdue_penalty_weight', models.DecimalField(decimal_places=2, default=25, max_digits=6)),
                ('severe_overdue_threshold_days', models.PositiveIntegerField(default=30)),
                ('trusted_min_score', models.DecimalField(decimal_places=2, default=80, max_digits=6)),
                ('moderate_min_score', models.DecimalField(decimal_places=2, default=60, max_digits=6)),
                ('watch_min_score', models.DecimalField(decimal_places=2, default=40, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_trust_rule_configs',
            },
        ),
        migrations.CreateModel(
            name='ClientTrustScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_type', models.CharField(max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('on_time_payment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('delayed_invoice_count', models.PositiveIntegerField(default=0)),
                ('overdue_invoice_count', models.PositiveIntegerField(default=0)),
                ('avg_days_to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('trust_level', models.CharField(default='watch', max_length=20)),
                ('flags_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_scores', to='core.client')),
            ],
            options={
                'db_table': 'client_trust_scores',
            },
        ),
        migrations.CreateModel(
            name='ProductivityRuleConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=100)),
                ('weight_on_time', models.DecimalField(decimal_places=2, default=33.33, max_digits=6)),
                ('weight_estimate_accuracy', models.DecimalField(decimal_places=2, default=33.33, max_digits=6)),
                ('weight_utilization', models.DecimalField(decimal_places=2, default=33.34, max_digits=6)),
                ('target_utilization_percent', models.DecimalField(decimal_places=2, default=80, max_digits=6)),
                ('overrun_penalty_factor', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'productivity_rule_configs',
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=50)),
                ('period_type', models.CharField(max_length=20)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('file_format', models.CharField(max_length=20)),
                ('file_id', models.CharField(blank=True, max_length=100)),
                ('export_status', models.CharField(default='queued', max_length=20)),
                ('requested_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_exports',
            },
        ),
        migrations.CreateModel(
            name='ReportingSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('snapshot_type', models.CharField(max_length=50)),
                ('period_type', models.CharField(max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reporting_snapshots',
            },
        ),
        migrations.CreateModel(
            name='ProductivityScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_type', models.CharField(max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utilization_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('on_time_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('variance_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('productivity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('breakdown_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productivity_scores', to='core.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productivity_scores', to='core.task')),
            ],
            options={
                'db_table': 'productivity_scores',
            },
        ),
        migrations.CreateModel(
            name='ClientTrustEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('days_delayed', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('score_impact', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_events', to='core.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_events', to='core.invoice')),
            ],
            options={
                'db_table': 'client_trust_events',
            },
        ),
    ]
