# Generated by Django 4.2.27 on 2026-02-17 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_calendar_kanban'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_disk', models.CharField(default='local', max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('visibility', models.CharField(default='private', max_length=20)),
                ('status', models.CharField(default='uploaded', max_length=20)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('week_start_day', models.CharField(default='monday', max_length=20)),
                ('default_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_due_days_default', models.PositiveIntegerField(default=7)),
                ('invoice_tax_default', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('invoice_prefix_default', models.CharField(default='INV', max_length=20)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=30)),
                ('time_format', models.CharField(default='24h', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspace_settings',
            },
        ),
    ]
